services:
  app:
    build: .
    image: app
    command: uvicorn main:app --host 0.0.0.0 --port 8083
    ports:
      - "8083:8083"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    